"""Content Engine — 'generate' stage Worker driver.

Run by the EOS Worker (via the generate-content-post skill). Performs the full EOS loop
for ONE job:  claim -> reason (draft generation) -> complete (persist structured JSON)
or  claim -> fail (retry / DLQ).

This is the SECOND stage of the Content Engine. It reuses the EXACT same EOS execution
spine as the 'score' stage (engines/_shared/eos_queue.py) — proof that one engine can
host multiple independent stages on the frozen platform with ZERO EOS changes.

The reasoning step (`reason_item`) submits the approved, scored item to the configured AI
Runtime via the runtime-agnostic OpenAI-compatible /v1/chat/completions contract and
normalizes the model's output to the frozen generate contract. The EOS does not name the
runtime, model, provider, or transport.

Credentials: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (and AI_RUNTIME_*) from the worker
environment. Never printed.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any, Optional

# EOS shared queue client lives at engines/_shared/ (single source of truth).
# run_generate_stage.py is at engines/content/lib/ -> up 3 levels to engines/, then _shared.
_HERE = os.path.realpath(__file__)
_SHARED = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(_HERE))), "_shared")
if _SHARED not in sys.path:
    sys.path.insert(0, _SHARED)

import eos_queue as ce_queue  # noqa: E402

ENGINE = "content"
STAGE = "generate"

# --------------------------------------------------------------------------
# Reasoning step — genuine AI Runtime reasoning (runtime-agnostic)
# --------------------------------------------------------------------------
# The EOS speaks the OpenAI-compatible /v1/chat/completions contract only. It does NOT
# know the runtime's name, model, provider, or transport. Those are Runtime concerns.

# Frozen generate contract — do NOT widen.
_TONES = ("professional", "casual", "thought_leadership")
_BODY_MAX = 1200  # hard cap (markdown)
_WORD_SOFT = 400  # soft target for word_count validation

_SYSTEM_PROMPT = (
    "You are a content generation engine. "
    "Given an approved, scored content item, draft a publication-ready social/editorial post. "
    "Respond with STRICT JSON only, no prose, matching exactly: "
    '{"draft_title": short string, '
    '"draft_body": markdown string <= 1200 chars, '
    '"tone": one of professional|casual|thought_leadership, '
    '"word_count": int}. '
    "The draft must be faithful to the source item and its editorial rationale. "
    "Do not invent facts not present in the source."
)


def _normalize(payload: dict, model: Optional[str]) -> dict:
    """Coerce model output into the frozen generate contract. Never invents fields."""
    draft_title = str(payload.get("draft_title", "")).strip()[:160] or "Untitled"

    draft_body = str(payload.get("draft_body", ""))
    if len(draft_body) > _BODY_MAX:
        draft_body = draft_body[:_BODY_MAX]

    tone = str(payload.get("tone", "")).strip().lower()
    if tone not in _TONES:
        tone = "professional"

    try:
        word_count = int(payload.get("word_count", 0))
    except (TypeError, ValueError):
        word_count = len(draft_body.split())
    word_count = max(0, word_count)

    result = {
        "draft_title": draft_title,
        "draft_body": draft_body,
        "tone": tone,
        "word_count": word_count,
    }
    # `model` proves the reasoning was generated by the AI Runtime (telemetry marker).
    if model:
        result["model"] = model
    return result


def reason_item(payload: dict) -> dict:
    """Submit the approved item to the AI Runtime and return a contract-conforming draft.

    Raises on transport/auth/parse failure so the caller's existing fail() path fires.
    """
    base = os.environ.get("AI_RUNTIME_BASE_URL")
    key = os.environ.get("AI_RUNTIME_API_KEY")
    if not base or not key:
        raise RuntimeError(
            "AI Runtime not configured: set AI_RUNTIME_BASE_URL and AI_RUNTIME_API_KEY"
        )

    title = payload.get("title") or ""
    content = payload.get("content") or ""
    score = payload.get("score")
    category = payload.get("category") or ""
    rationale = payload.get("rationale") or ""
    source_url = payload.get("source_url") or ""
    user = (
        f"Title: {title}\n"
        f"Content: {content}\n"
        f"Source URL: {source_url}\n"
        f"Editorial score: {score} (category: {category})\n"
        f"Editorial rationale: {rationale}"
    )

    import requests  # available in the worker runtime

    resp = requests.post(
        f"{base.rstrip('/')}/chat/completions",
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        json={
            "model": os.environ.get("AI_RUNTIME_MODEL", ""),
            "messages": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.4,
        },
        timeout=90,
    )
    resp.raise_for_status()
    data = resp.json()
    model = data.get("model")
    content_str = ""
    choices = data.get("choices") or []
    if choices:
        content_str = choices[0].get("message", {}).get("content", "") or ""
    parsed = json.loads(content_str)  # raises on malformed -> fail() path
    return _normalize(parsed, model)


def main() -> int:
    try:
        job = ce_queue.claim(ENGINE, STAGE)
    except Exception as e:  # noqa: BLE001
        print(f"[generate] claim error: {e}", file=sys.stderr)
        return 2

    if job is None:
        print("[generate] queue empty for stage=generate — nothing to do.")
        return 0

    job_id = job["id"]
    payload = job.get("payload_json") or {}
    source_url = payload.get("source_url")
    print(f"[generate] claimed job {job_id} source={source_url}")

    try:
        result = reason_item(payload)
        ce_queue.complete(job_id, result, source_url=source_url)
        # Chain (ADR-026): a successful generate enqueues the REVIEW stage — NOT publish.
        # The draft is untrusted input to Review, which pressure-tests it. Publish jobs are
        # created ONLY by the Selection mechanism (EOM §8) from the Approved Pool.
        # This produces the "Pending Review" job: stage="review", status="pending".
        ce_queue.enqueue(
            ENGINE, "review",
            {
                "source_url": source_url,
                "draft_title": result.get("draft_title", ""),
                "draft_body": result.get("draft_body", ""),
                "tone": result.get("tone", ""),
                "generated_from": payload,
            },
        )
        print(f"[generate] completed job {job_id} -> {result} (enqueued review)")
        return 0
    except Exception as e:  # noqa: BLE001
        err = f"{type(e).__name__}: {e}"[:500]
        ce_queue.fail(job_id, err)
        print(f"[generate] failed job {job_id}: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
