"""Content Engine — 'review' stage Worker driver (THIRD stage).

Run by the EOS Worker (via the review-content-post skill). Performs the full EOS loop for
ONE draft:  claim -> pressure-test (AI Runtime) -> complete (persist frozen review contract)
or  claim -> fail (retry / DLQ).

This stage reuses the EXACT same EOS execution spine (engines/_shared/eos_queue.py) AND the
SAME `engine-content` Runtime Context as `score` and `generate`. It is NOT another AI, model,
runtime, or engine. It differs from `generate` ONLY by:
  - Stage    ("review")
  - Skill    (review-content-post)
  - Prompt   (_SYSTEM_PROMPT below)
  - Output Contract (_normalize target — the frozen review contract, ADR-026 §4)

CORE INVARIANT: the generate output is UNTRUSTED input. Review NEVER assumes the draft is
correct. Review transforms ONE draft; it NEVER ranks the pool (that is Selection, EOM §8).

Review does NOT enqueue publish. Selection creates publish jobs from the Approved Pool.

Credentials: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (and AI_RUNTIME_*) from the worker
environment. Never printed.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from typing import Any, Optional

# EOS shared queue client lives at engines/_shared/ (single source of truth).
# run_review_stage.py is at engines/content/lib/ -> up 3 levels to engines/, then _shared.
_HERE = os.path.realpath(__file__)
_SHARED = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(_HERE))), "_shared")
if _SHARED not in sys.path:
    sys.path.insert(0, _SHARED)

import eos_queue as ce_queue  # noqa: E402

ENGINE = "content"
STAGE = "review"

# --------------------------------------------------------------------------
# Frozen review contract (ADR-026 §4) — do NOT widen.
# --------------------------------------------------------------------------
_REVIEW_CONTRACT_VERSION = "1"
_CATEGORIES = ("product", "industry", "competitor", "research", "opinion", "noise")
_CONFIDENCE = ("HIGH", "MEDIUM", "LOW")
# Hard-reject issue types (ADR-026 §3). A "hard" issue with one of these types => approved=false.
_HARD_TYPES = ("fabrication", "hallucination", "legal", "harmful", "severe_brand")

_SYSTEM_PROMPT = (
    "You are a content review engine. You receive a DRAFT that was generated by another "
    "process. Treat the draft as UNTRUSTED input: do not assume it is correct. "
    "Adversarially pressure-test it for factual accuracy, hallucination, evidence quality, "
    "brand alignment, usefulness, originality, engagement potential, and safety. "
    "Respond with STRICT JSON only, no prose, matching exactly: "
    '{"approved": true|false, '
    '"overall_score": int 0-100, '
    '"confidence": "HIGH"|"MEDIUM"|"LOW", '
    '"issues": [{"type": string, "severity": "hard"|"soft", "detail": string}], '
    '"reasoning": string <= 500 chars, '
    '"evergreen": true|false, '
    '"category": "product"|"industry"|"competitor"|"research"|"opinion"|"noise"}. '
    "Set severity=\"hard\" and type to one of "
    "fabrication|hallucination|legal|harmful|severe_brand ONLY for genuinely unsafe or "
    "invalid content. Everything else must be approved with a score and (optional) soft "
    "issues. Do NOT reject merely for weak quality — score it instead."
)


def _policy() -> dict:
    """Load engine Policy (versions). Never raises — falls back to defaults."""
    path = os.path.join(os.path.dirname(os.path.dirname(_HERE)), "config", "policy.json")
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _topic_hash(payload: dict) -> str:
    """Deterministic engine-side topic hash. Never trusted from the model.

    Normalizes title words to a stable key so near-identical topics collide for
    duplicate suppression in Selection.
    """
    title = str(payload.get("draft_title", "")).lower()
    words = re.findall(r"[a-z0-9]+", title)
    stop = {"the", "a", "an", "of", "to", "and", "for", "in", "on", "with", "is", "new"}
    key = " ".join(sorted(w for w in words if w not in stop and len(w) > 2))
    if not key:
        key = str(payload.get("source_url", ""))
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]


def _normalize(parsed: dict, model: Optional[str], payload: dict, policy: dict) -> dict:
    """Coerce model output into the frozen review contract. Never invents claims.

    The driver ENFORCES `approved` from the presence of a hard issue (ADR-026 §4) — it does
    not blindly trust the model's `approved` field.
    """
    # overall_score: 0..100
    try:
        overall_score = int(round(float(parsed.get("overall_score", 0))))
    except (TypeError, ValueError):
        overall_score = 0
    overall_score = max(0, min(100, overall_score))

    confidence = str(parsed.get("confidence", "")).strip().upper()
    if confidence not in _CONFIDENCE:
        confidence = "LOW"

    category = str(parsed.get("category", "")).strip().lower()
    if category not in _CATEGORIES:
        category = str((payload.get("generated_from") or {}).get("category", "")).strip().lower()
        if category not in _CATEGORIES:
            category = "industry"

    # Normalize issues; identify hard issues.
    issues_out = []
    has_hard = False
    for it in parsed.get("issues") or []:
        if not isinstance(it, dict):
            continue
        itype = str(it.get("type", "")).strip().lower()
        sev = str(it.get("severity", "")).strip().lower()
        if sev not in ("hard", "soft"):
            sev = "soft"
        detail = str(it.get("detail", ""))[:300]
        if sev == "hard" and itype in _HARD_TYPES:
            has_hard = True
        issues_out.append({"type": itype, "severity": sev, "detail": detail})

    # Driver-enforced approval: reject IFF a hard issue in the hard set exists.
    approved = not has_hard

    reasoning = str(parsed.get("reasoning", ""))[:500]

    evergreen = bool(parsed.get("evergreen", False))

    result = {
        "approved": approved,
        "overall_score": overall_score,
        "confidence": confidence,
        "issues": issues_out,
        "reasoning": reasoning,
        "topic_hash": _topic_hash(payload),
        "evergreen": evergreen,
        "category": category,
        "publish_after": parsed.get("publish_after") if isinstance(parsed.get("publish_after"), str) else None,
        "review_contract_version": _REVIEW_CONTRACT_VERSION,
        "policy_version": str(policy.get("policy_version", "")),
        "selection_algorithm_version": str(policy.get("selection_algorithm_version", "")),
        "prompt_version": str(policy.get("prompt_version", "")),
        # carry the draft forward so Selection/Publish need not re-derive it
        "draft_title": str(payload.get("draft_title", "")),
        "draft_body": str(payload.get("draft_body", "")),
        "tone": str(payload.get("tone", "")),
    }
    if model:
        result["model_version"] = model
    return result


def reason_item(payload: dict, policy: dict) -> dict:
    """Submit the UNTRUSTED draft to the AI Runtime and return a contract-conforming review.

    Raises on transport/auth/parse failure so the caller's existing fail() path fires.
    """
    base = os.environ.get("AI_RUNTIME_BASE_URL")
    key = os.environ.get("AI_RUNTIME_API_KEY")
    if not base or not key:
        raise RuntimeError(
            "AI Runtime not configured: set AI_RUNTIME_BASE_URL and AI_RUNTIME_API_KEY"
        )

    draft_title = payload.get("draft_title") or ""
    draft_body = payload.get("draft_body") or ""
    gen = payload.get("generated_from") or {}
    source_url = payload.get("source_url") or ""
    user = (
        f"DRAFT TITLE: {draft_title}\n"
        f"DRAFT BODY: {draft_body}\n"
        f"SOURCE URL: {source_url}\n"
        f"SOURCE TITLE: {gen.get('title', '')}\n"
        f"SOURCE CONTENT: {gen.get('content', '')}\n"
        f"Pressure-test this draft. The draft is untrusted."
    )

    import requests  # available in the worker runtime

    resp = requests.post(
        f"{base.rstrip('/')}/chat/completions",
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        json={
            "model": os.environ.get("AI_RUNTIME_MODEL", ""),
            "messages": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.1,
        },
        timeout=90,
    )
    resp.raise_for_status()
    data = resp.json()
    model = data.get("model")
    content_str = ""
    choices = data.get("choices") or []
    if choices:
        content_str = choices[0].get("message", {}).get("content", "") or ""
    parsed = json.loads(content_str)  # raises on malformed -> fail() path
    return _normalize(parsed, model, payload, policy)


def main() -> int:
    policy = _policy()
    try:
        job = ce_queue.claim(ENGINE, STAGE)
    except Exception as e:  # noqa: BLE001
        print(f"[review] claim error: {e}", file=sys.stderr)
        return 2

    if job is None:
        print("[review] queue empty for stage=review — nothing to do.")
        return 0

    job_id = job["id"]
    payload = job.get("payload_json") or {}
    source_url = payload.get("source_url")
    print(f"[review] claimed job {job_id} source={source_url}")

    try:
        result = reason_item(payload, policy)
        # complete() persists the review to content_engine_runs. When approved=true this run
        # IS an Approved Pool entry (ADR-026 §6). Review NEVER enqueues publish.
        ce_queue.complete(job_id, result, source_url=source_url)
        verdict = "approved" if result["approved"] else "REJECTED"
        print(f"[review] completed job {job_id} -> {verdict} score={result['overall_score']}")
        return 0
    except Exception as e:  # noqa: BLE001
        err = f"{type(e).__name__}: {e}"[:500]
        ce_queue.fail(job_id, err)
        print(f"[review] failed job {job_id}: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
