"""Content Engine — 'score' stage Worker driver.

Run by the EOS Worker (via the score-content-source skill). Performs the full EOS loop
for ONE job:  claim -> reason (scoring) -> complete (persist structured JSON)
or  claim -> fail (retry / DLQ).

The reasoning step (`reason_item`) submits the item to the configured AI Runtime via the
runtime-agnostic OpenAI-compatible /v1/chat/completions contract and normalizes the model's
output to the frozen score contract (0-10, fixed categories, approve/reject). The EOS does
not name the runtime, model, provider, or transport.

Credentials: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (and AI_RUNTIME_*) from the worker
environment. Never printed.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any, Optional

# EOS shared queue client lives at engines/_shared/ (single source of truth).
# run_score_stage.py is at engines/content/lib/ -> up 3 levels to engines/, then _shared.
_HERE = os.path.realpath(__file__)
_SHARED = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(_HERE))), "_shared")
if _SHARED not in sys.path:
    sys.path.insert(0, _SHARED)

import eos_queue as ce_queue  # noqa: E402

ENGINE = "content"
STAGE = "score"

# --------------------------------------------------------------------------
# Reasoning step — genuine AI Runtime reasoning (runtime-agnostic)
# --------------------------------------------------------------------------
# The EOS speaks the OpenAI-compatible /v1/chat/completions contract only. It does NOT
# know the runtime's name, model, provider, or transport. Those are Runtime concerns.
# EOS reads two generic facts:
#   AI_RUNTIME_BASE_URL  e.g. http://127.0.0.1:8642/v1
#   AI_RUNTIME_API_KEY   bearer token for the runtime's API server
# If a future runtime (e.g. OpenCode) exposes the same contract, EOS is unchanged.

# Frozen contract (from score-content-source SKILL.md) — do NOT widen.
_CATEGORIES = ("product", "industry", "competitor", "research", "opinion", "noise")
_SCORE_MAX = 10  # contract scale is 0..10
_SYSTEM_PROMPT = (
    "You are a content scoring engine. "
    "Given a content item, decide its editorial relevance and quality. "
    "Respond with STRICT JSON only, no prose, matching exactly: "
    '{"score": int 0-10, "category": one of '
    "product|industry|competitor|research|opinion|noise, "
    '"decision": "approve" or "reject", "rationale": short string <= 280 chars}. '
    "Approve when score >= 4."
)


def _normalize(payload: dict, model: Optional[str]) -> dict:
    """Coerce model output into the frozen contract. Never invents fields."""
    raw_score = payload.get("score")
    try:
        score = int(round(float(raw_score)))
    except (TypeError, ValueError):
        score = 0
    if score > _SCORE_MAX:
        score = max(0, min(_SCORE_MAX, round(score * _SCORE_MAX / 100)))
    score = max(0, min(_SCORE_MAX, score))

    category = str(payload.get("category", "")).strip().lower()
    if category not in _CATEGORIES:
        category = "industry"

    decision = str(payload.get("decision", "")).strip().lower()
    if decision not in ("approve", "reject"):
        decision = "approve" if score >= 4 else "reject"

    rationale = str(payload.get("rationale", ""))[:280]

    result = {
        "score": score,
        "category": category,
        "decision": decision,
        "rationale": rationale,
    }
    # `model` proves the reasoning was generated by the AI Runtime (telemetry marker).
    if model:
        result["model"] = model
    return result


def reason_item(payload: dict) -> dict:
    """Submit the item to the AI Runtime and return a contract-conforming result.

    Raises on transport/auth/parse failure so the caller's existing fail() path fires.
    """
    base = os.environ.get("AI_RUNTIME_BASE_URL")
    key = os.environ.get("AI_RUNTIME_API_KEY")
    if not base or not key:
        raise RuntimeError(
            "AI Runtime not configured: set AI_RUNTIME_BASE_URL and AI_RUNTIME_API_KEY"
        )

    title = payload.get("title") or ""
    content = payload.get("content") or ""
    user = f"Title: {title}\nContent: {content}"

    import requests  # available in the worker runtime

    resp = requests.post(
        f"{base.rstrip('/')}/chat/completions",
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        json={
            "model": os.environ.get("AI_RUNTIME_MODEL", ""),
            "messages": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2,
        },
        timeout=90,
    )
    resp.raise_for_status()
    data = resp.json()
    model = data.get("model")
    content_str = ""
    choices = data.get("choices") or []
    if choices:
        content_str = choices[0].get("message", {}).get("content", "") or ""
    parsed = json.loads(content_str)  # raises on malformed -> fail() path
    result = _normalize(parsed, model)
    _carry_provenance(result, payload)
    return result


# Provenance preservation (ENGINE-009). The collector attaches an immutable evidence
# contract to every opportunity. These fields identify the raw collector artifact and MUST
# survive untouched through the whole downstream pipeline so the Approved Pool remains
# auditable back to source. They ride existing result_json/payload_json jsonb — no schema,
# stage, or queue change, and no reasoning stage interprets them.
_PROVENANCE_FIELDS = ("raw_evidence_ref", "record_key", "collector_version", "endpoint")


def _carry_provenance(dst: dict, src: dict) -> None:
    """Copy the collector provenance contract from src -> dst if present (never invents)."""
    for _k in _PROVENANCE_FIELDS:
        if src.get(_k) is not None:
            dst[_k] = src.get(_k)


def main() -> int:
    try:
        job = ce_queue.claim(ENGINE, STAGE)
    except Exception as e:  # noqa: BLE001
        print(f"[score] claim error: {e}", file=sys.stderr)
        return 2

    if job is None:
        print("[score] queue empty for stage=score — nothing to do.")
        return 0

    job_id = job["id"]
    payload = job.get("payload_json") or {}
    source_url = payload.get("source_url")
    print(f"[score] claimed job {job_id} source={source_url}")

    try:
        result = reason_item(payload)
        ce_queue.complete(job_id, result, source_url=source_url)
        print(f"[score] completed job {job_id} -> {result}")
        return 0
    except Exception as e:  # noqa: BLE001
        err = f"{type(e).__name__}: {e}"[:500]
        ce_queue.fail(job_id, err)
        print(f"[score] failed job {job_id}: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
